<?php
require_once __DIR__ . '/helpers.php';

$L    = 7;
$meta = bp_levels()[$L];

// Exactly the recipe the source panel shows, and exactly what render.php runs.
$nonce  = bp_daily_nonce();
$policy = bp_policy($L, $nonce);

$payload = (string)($_POST['payload'] ?? '');
$flag    = '';
$result  = '';
$stages  = [];
$frame   = '';

if ($payload !== '') {
    $eval   = csp_evaluate($policy, $payload, [
        'page_url'     => bp_render_url($L),
        'page_scripts' => [
            ['label' => "the page's own <script nonce src=\"frame.js\">", 'kind' => 'external',
             'src' => 'frame.js', 'nonce' => $nonce],
        ],
    ]);
    $stages = csp_stages($eval);

    // The effect that matters: a script from the injection ran.
    $ran = csp_executed($eval, 'injection');

    $frame = bp_frame($L, ['i' => $payload],
        'render.php recomputes the nonce with the same code before sending the header, so what you see here is the '
        . 'browser enforcing the real policy.');

    if ($ran) {
        $flag   = bp_flag($L);
        $result = bp_verdict(true,
            'Your script executed under a nonce policy. It was allowed by <code>'
            . lk_esc($ran[0]['directive']) . '</code>, which means you presented a value only the server was '
            . 'supposed to know.');
    } else {
        $result = bp_verdict(false,
            'Nothing in that markup runs under this policy. The trace names the directive that refused each node.');
    }
}

/* A small demonstration that the value is not merely reused but predictable. */
$diary = [
    'yesterday' => bp_daily_nonce(-1),
    'today'     => bp_daily_nonce(0),
    'tomorrow'  => bp_daily_nonce(1),
];

$code = <<<'PHP'
// "Nonces are the recommended CSP. Rolled out last sprint."
//
// mt_rand() needs a seed. Seeding it per request looked wasteful in
// profiling, so it was moved to one seed per day.
mt_srand((int)(time() / 86400));
$nonce = dechex(mt_rand());

header("Content-Security-Policy: "
     . "default-src 'self'; "
     . "script-src 'nonce-$nonce'; "
     . "object-src 'none'");

// The page's own scripts carry the nonce.
echo '<script nonce="' . $nonce . '" src="frame.js"></script>';

// The note is still written into the document as HTML.
echo '<div id="note">' . $note . '</div>';
PHP;

$fixBad = <<<'PHP'
mt_srand((int)(time() / 86400));      // one seed per day
$nonce = dechex(mt_rand());           // therefore one nonce per day
header("Content-Security-Policy: script-src 'nonce-$nonce'");
PHP;

$fixGood = <<<'PHP'
// A nonce has to be unpredictable AND used once. Both properties come
// from generating it per response with a cryptographic source.
$nonce = base64_encode(random_bytes(16));   // 128 bits, new every response

header("Content-Security-Policy: "
     . "default-src 'self'; "
     . "script-src 'nonce-$nonce' 'strict-dynamic'; "
     . "object-src 'none'; base-uri 'none'");

// Caching matters as much as generation: a response carrying a nonce
// must never be stored and replayed to another visitor.
header('Cache-Control: no-store');
PHP;

lk_page([
    'lab'        => bp_lab(),
    'level'      => $L,
    'title'      => $meta['title'],
    'difficulty' => $meta['difficulty'],
    'extra_head' => bp_extra_head(),

    'code'       => $code,
    'vuln_lines' => [5, 6],
    'annotation' => 'The nonce is generated by a non-cryptographic generator seeded with a day counter. Every
        response served today carries the same value, so a nonce that was meant to be a one-time ticket is a
        password that an attacker reads off any response and reuses.',

    'theory' => '<p>A nonce works by naming a specific tag rather than a location. The server prints a fresh value
        in the header and on the tags it wrote itself; an injected tag cannot carry the value because the attacker
        has not seen this response. That argument depends on two properties, and losing either one is fatal.</p>
        <p><strong>Unpredictable.</strong> <code>mt_rand()</code> is a Mersenne Twister: fast, uniform, and entirely
        deterministic given the seed. Seeded with a day counter, tomorrow&rsquo;s nonce can be computed today, and
        so can every nonce for the rest of the decade. Even seeded with a timestamp, the search space is small
        enough to enumerate.</p>
        <p><strong>Used once.</strong> Reuse is the more common failure and the more subtle one, because it can
        happen without anyone touching the generator: a nonce placed in a cached page, a nonce stored in the session
        so that "the assets keep working", a static HTML file with a hard-coded nonce shipped alongside a header set
        by the web server. In each case the attacker gets the value from a response they are entitled to see and
        replays it into the victim&rsquo;s page.</p>
        <p>The consequence to internalise: a nonce is a secret with a lifetime of exactly one response. If you can
        write it down, it is not doing its job.</p>',

    'fix' => [
        'bad'  => $fixBad,
        'good' => $fixGood,
        'note' => 'Use the platform&rsquo;s cryptographic source and generate inside the response, not around it.
            <code>random_bytes()</code> in PHP, <code>secrets.token_urlsafe()</code> in Python,
            <code>crypto.randomBytes()</code> in Node. Then make sure nothing caches the response: a page with a
            nonce and a shared cache entry is a reused nonce with extra steps.',
    ],

    'scenario' => '<strong>Scenario:</strong> the storefront replaced its allowlist with a nonce, which closes the
        JSONP gadget from level 6 &mdash; no endpoint on the origin can produce a tag carrying the nonce.
        <br><strong>Goal:</strong> run inline script in the frame anyway.',

    'model' => [
        'title' => 'The same generator, three days running',
        'html'  => '<table class="lk-kv">
            <tr><td>seed</td><td><code>(int)(time() / 86400)</code> &mdash; a day counter, currently
                <code>' . (int)(time() / 86400) . '</code></td></tr>
            <tr><td>yesterday</td><td><code>' . lk_esc($diary['yesterday']) . '</code></td></tr>
            <tr><td>today</td><td><code>' . lk_esc($diary['today']) . '</code></td></tr>
            <tr><td>tomorrow</td><td><code>' . lk_esc($diary['tomorrow']) . '</code></td></tr>
        </table>
        <p>Those three values were computed here, now, by running the same two lines the source panel shows. That is
        the predictability half of the problem. The reuse half is simpler still: today&rsquo;s value is printed in
        the <code>Content-Security-Policy</code> header of the response you are reading, and it will still be valid
        for every visitor until midnight.</p>
        <p>The policy this frame sends right now:</p>
        <div class="bp-policy">' . lk_esc($policy) . '</div>',
    ],

    'form'   => bp_markup_form($payload, 'Markup injected into the frame',
        '<script nonce="...">hlab.win()</script>', 'Inject and render'),
    'result' => $result . $frame,
    'flag'   => $flag,
    'flag_msg' => 'A value you were able to read is not a nonce.',
    'why'    => '<p>The browser compared the <code>nonce</code> attribute on your script element with the nonce in
        the policy, found them equal, and ran the script. That is the mechanism working correctly &mdash; the
        failure is upstream, in the decision to make the value knowable.</p>
        <p>Notice that you never had to defeat anything. You copied a string out of a header and pasted it into an
        attribute. Any attacker who can fetch one page from this site can do the same, and with the day-seeded
        generator they do not even need to fetch it.</p>
        <p>When you audit a nonce deployment, ask three questions: where does the randomness come from, does the
        value change between two fetches of the same URL, and can any cache store a response that contains it.</p>',

    'pipeline' => $stages,
    'probes'   => [
        'param'  => 'payload',
        'method' => 'POST',
        'action' => 'level7.php',
        'items'  => [
            ['q'       => 'Does an inline script without a nonce run?',
             'payload' => '<script>hlab.win()</script>',
             'learn'   => 'The baseline refusal. It confirms the policy has no <code>&#39;unsafe-inline&#39;</code> '
                        . 'and that the nonce attribute is the only way in.'],
            ['q'       => 'Does a wrong nonce fail, or is the attribute merely decorative?',
             'payload' => '<script nonce="not-the-nonce">hlab.win()</script>',
             'learn'   => 'A refusal proves the value is really compared. Some misconfigurations accept any nonce '
                        . 'attribute at all, and it is worth ruling that out before you go looking for the value.'],
            ['q'       => 'Does the level-6 gadget still work here?',
             'payload' => '<script src="/jsonp.php?callback=renderProducts"></script>',
             'learn'   => 'A refusal is the point: nonces are what closes host-allowlist gadgets. It also tells you '
                        . 'the policy has no host sources left to attack.'],
        ],
    ],
    'hints' => bp_hints($L),
]);
