#!/usr/bin/env bash
# Rebuild every lab's stylesheet from its parts:
#
#   css/base.css   the lab's original layout and components (unchanged)
#   _kit/kit.css   the teaching layer
#   _kit/retro.css the Turbo Vision theme
#
# The build hoists the font imports to the top (an @import after a rule is
# ignored) and swaps the two original families for their IBM Plex counterparts,
# so the source files stay readable and the theme stays in one place.
#
#   ./_kit/build-css.sh          # every lab
#   ./_kit/build-css.sh "JWT Lab"
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

IMPORTS="@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600;700&family=Silkscreen:wght@400;700&display=swap');"

build_one() {
  local dir="$1"
  [ -f "$dir/css/base.css" ] || { echo "  skip $dir (no base.css)"; return; }

  {
    echo "/* Generated by _kit/build-css.sh — edit base.css, kit.css or retro.css, not this file. */"
    echo "$IMPORTS"
    echo
    # Drop the original @import, and point the old family names at IBM Plex.
    sed -e "/^@import/d" \
        -e "s/'Inter'/'IBM Plex Sans'/g" \
        -e "s/'JetBrains Mono'/'IBM Plex Mono'/g" \
        "$dir/css/base.css"
    echo
    cat "$ROOT/_kit/kit.css"
    echo
    sed -e "/^@import/d" "$ROOT/_kit/retro.css"
  } > "$dir/css/styles.css"

  printf '  %-24s %s lines\n' "$dir" "$(wc -l < "$dir/css/styles.css")"
}

if [ $# -gt 0 ]; then
  for d in "$@"; do build_one "$d"; done
else
  echo "Rebuilding stylesheets:"
  for f in */css/base.css; do build_one "$(dirname "$(dirname "$f")")"; done
fi
