services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sqli_lab
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-files:/var/lib/mysql-files
    ports:
      - "3306:3306"
    command: --secure-file-priv=/var/lib/mysql-files --sql_mode="" --authentication-policy=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10
  web:
    image: php:8.0-apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=sqli_lab
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql
      && apache2-foreground"